version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  settings:
    goimports:
      local-prefixes: github.com/rocky-linux/mattermost-plugin-community-toolkit
    govet:
      enable:
        - shadow
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

  exclusions:
    rules:
      - path: server/configuration.go
        linters:
          - unused
      - path: server/manifest.go
        linters:
          - misspell
      - path: _test\.go
        linters:
          - bodyclose
      - linters:
          - revive
        text: unused-parameter

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true